track._MetadataCacher: Fix error when the time is the same (#718)
If tracks are added to the cacher fast enough, multiple entries can have
the same time (i[2]). This then causes the min((i[2], i) ...) call to end
up comparing the track objects (i[0]), causing a spurious error preventing
the Track Properties dialog from opening:

    TypeError: '<' not supported between instances of 'Track' and 'Track'

After this change, the code will pick any arbitrary item with the lowest
time value.