Don't remove tracks twice during scan.
A bug was introduced in #885 by potentially adding tracks to `removals`
twice if both conditions are true. This results in a KeyError when
removal of the second track is attempted because the `location` has
already been deleted from `self.tracks`:

    File "./xl/trax/trackdb.py", line 369, in remove_tracks
      self._deleted_keys.append(self.tracks[location]._key)
    KeyError: 'file:///...'